AWSTemplateFormatVersion: 2010-09-09
Description: 'AWS cloudformation stack for userpool,client and table'
Parameters:
  AuthName:
    Type: String
    Description: Input tenant Name
Resources:
  UserPool:
    Type: 'AWS::Cognito::UserPool'
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - verified_email
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
        InviteMessageTemplate:
          EmailMessage: Your account is created
          EmailSubject: AWS Account
      AliasAttributes:
        - email
      AutoVerifiedAttributes:
        - phone_number
      DeletionProtection: 'NO'
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      VerificationMessageTemplateType:
        DefaultEmailOption: CONFIRM_WITH_CODE
      MfaConfiguration: 'OFF'
      Schema:
        - AttributeDataType: String
          Mutable: true
          Name: name
          Required: true
        - AttributeDataType: String
          Mutable: true
          Name: phone_number
          Required: true
        - AttributeDataType: String
          Mutable: true
          Name: tenant_id
          Required: true
        - AttributeDataType: String
          Mutable: true
          Name: userpool_id
          Required: true
        - AttributeDataType: String
          Mutable: true
          Name: password
          Required: true
        - AttributeDataType: String
          Mutable: true
          Name: email
          Required: true
      UsernameAttributes:
        - email
      UserPoolName:
        data: '{AuthName}-user-pool'
        type: Sub
        isCfnFunction: true
  UserPoolClient:
    Type: 'AWS::Cognito::UserPoolClient'
    Properties:
      ClientName:
        data: '${AuthName}-client'
        type: Sub
        isCfnFunction: true
      GenerateSecret: false
      UserPoolId: !Ref UserPool
  
Outputs:
  UserPoolId:
    Value:
      Ref: UserPool
      Export:
        Name: 'userpool::id'
  ClientId:
    Value:
      Ref: UserPoolClient
      Export:
        Name: 'client::id'

